### ISSUE TITLE
Installation of self-hosted version fails / stucks

### ISSUE THREAD

**Issue by tetsuoinc** [alextselegidis/plainpad#2]
Hi Alex,
According to your description [here ](https://alextselegidis.com/get/plainpad/self-hosted)...

> Alternatively you can open the browser to the /url/to/public/setup.php file and submit the installation form.

I've uploaded all the contents of the ZIP-File to a shared webhosting.

I've set up a subdomain https://notes.example.com which pointed to the "public" directory.

Then I opened https://notes.example.com/setup.php which leads me to the database-form.

I filled the form with the database credentials (double checked them for correctness!) and hit the Install-Button.

No errors, no warnings, no success message apperead and the browser points now to https://notes.example.com/#/login.

As I have no login credentials, I'm stuck right here.
I checked the database, but there was no table inside. 

What am I doing wrong and what can I do ?

**Comment by crendl** [comment]
in case i understood you correctly, you managed to install plainpad correctly and now are missing login credentials?

default credentials are 
username: admin@example.org
password: 12345

**Comment by alextselegidis** [comment]
@tetsuoinc Did you manage to login?

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Closing due to inactivity

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rob360** [comment]
Hello,

I have exactly the same problem. I tried the default credentials: username:
admin@example.org
password: 12345

but no success.

**Comment by raystek** [comment]
I am having the same issue. The version is 1.0.0-beta.4. After I entered the info into the setup.php page and clicked Install, it brought me to the login page. But the above default credentials don't work. 

Also, tried using "php artisan migrate:fresh --seed" and got database error: 
---
Illuminate\Database\QueryException 

  could not find driver (SQL: select * from information_schema.tables where table_schema = rsnotesdb and table_name = settings and table_type = 'BASE TABLE')
---
rsnotesdb is my sql database

**Comment by alextselegidis** [comment]
Alright I'm reopening this issue with further troubleshooting as it looks like it affects more users. 

First things first, there are two reasons for this issue: 

* The seed command was not executed properly so there is no admin record in the database. 
*  HTTP requests are not routed correctly and that means that JS cannot perform the login request properly. 

It is important to understand which of the two cases are applied for you. 

In order to do that, you will need to check your database and see if there's an admin user record in the `users` table. 

If there's no record or no table at all, then the migration/seeding failed. 

If there is a record then you can open your browser developer tools by pressing F12 and open the "console" tab inside them. 

After you reload the page you should be able to see errors in there, please post them here for further troubleshooting. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by guillaumesoucy94** [comment]
Hello, 

Same issue here as well, the credentials did not work. I did the setup with setup.php and it create a .env file at the root.

Plus when doing:

`php artisan migrate:fresh --seed`

I've this:
`   ErrorException 

  Undefined index: mail_driver

  at vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1367
    1363▕      * @return mixed
    1364▕      */
    1365▕     public function offsetGet($key)
    1366▕     {
  ➜ 1367▕         return $this->items[$key];
    1368▕     }
    1369▕ 
    1370▕     /**
    1371▕      * Set the item at a given offset.

      +1 vendor frames 
  2   app/Providers/MailConfigServiceProvider.php:42
      Illuminate\Support\Collection::offsetGet()

      +7 vendor frames 
  10  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()`




![Screenshot at 2022-01-25 13-05-45](https://user-images.githubusercontent.com/22561876/151034154-19414c12-6fa9-444f-95fe-059ca2c23947.png)

The database and the user for mysql are present.

How to fix it and make it work?

Regards, 

Guillaume

**Comment by mvalley21** [comment]
I ran into similar issues getting this to work. 

First, you must run php artisan migrate:fresh --seed to properly create the user table. You'll see something like:
Login with the default admin user (email: admin@example.org & password: 12345).
Seeded:  Database\Seeders\UsersSeeder (48.63ms)
Seeding: Database\Seeders\SettingsSeeder
Seeded:  Database\Seeders\SettingsSeeder (10.35ms)
Database seeding completed successfully.
if it worked correctly.

Second issue was I personally am running ngnix and only .htaccess files for apache are included
Here's the equiv for ngnix to make the api calls work:
     location /plainpad/public/api.php/v1/ {
          try_files $uri $uri/ /plainpad/public/api.php?$args;
        }

**Comment by guillaumesoucy94** [comment]
Thanks it works now! ;-) I hope it gonna help peoples encountering the same issue. 

![Screenshot Plainpad 1](https://user-images.githubusercontent.com/22561876/154311653-de6585af-e261-4df7-854d-10fe1c3df994.png)

**Comment by alextselegidis** [comment]
Thanks for all your input! This will be fixed for the next version.

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by julyprum** [comment]
Hello Alex, here reopening this thread. I am having this same issue on my Synology NAS. I have ran the setup.php and added the nginx lines. My JS console is throwing some errors that I think are due to missing Laravel files. 

For example:
plainpad/vendor/laravel/framework/src/Illuminate/Routing/Matching/MethodValidator.php
plainpad/vendor/laravel/framework/src/Illuminate/Routing/Matching/SchemeValidator.php

after adding those 2 files, i was able to login and use the app. hope it helps.

**Comment by alextselegidis** [comment]
Hello! 

@julyprum Thanks for posting this! Could it be that the files were not uploaded correctly or do you think the files are missing from the archive?

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by j-r-e-i-d** [comment]
> I ran into similar issues getting this to work.
> 
> First, you must run php artisan migrate:fresh --seed to properly create the user table. You'll see something like: Login with the default admin user (email: [admin@example.org](mailto:admin@example.org) & password: 12345). Seeded: Database\Seeders\UsersSeeder (48.63ms) Seeding: Database\Seeders\SettingsSeeder Seeded: Database\Seeders\SettingsSeeder (10.35ms) Database seeding completed successfully. if it worked correctly.
> 
> Second issue was I personally am running ngnix and only .htaccess files for apache are included Here's the equiv for ngnix to make the api calls work: location /plainpad/public/api.php/v1/ { try_files $uri $uri/ /plainpad/public/api.php?$args; }

can you explain how I make this work please? I am on nginx and cannot log in with default credentials. The user has been created in the database

**Comment by alextselegidis** [comment]
@j-r-e-i-d Can you make sure your DB is seeded, by checking the default admin@example.org record inside the users table? 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by j-r-e-i-d** [comment]
Oh man I gave up on this weeks ago. Too hard. I use Joplin now

**Comment by ljgww** [comment]
also running nginx, also stuck on login - added 'location' config to nginx.

artisan have problem to work (not only to seed)

ubuntu 22



$ php artisan
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1354
Stack trace:
#0 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(11): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/pp/vendor/composer/ClassLoader.php(444): include('...')
#2 /var/www/html/pp/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()
#5 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation\PackageManifest->config()
#6 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#7 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#8 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith()
#9 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundation\Console\Kernel->bootstrap()
#10 /var/www/html/pp/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#11 {main} in /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Collections/Collection.php on line 11

In Collection.php line 11:
                                                                               
  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of   
  Illuminate\Support\Collection::offsetExists($key) should either be compatib  
  le with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTyp  
  eWillChange] attribute should be used to temporarily suppress the notice in  
   /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Collections/Colle  
  ction.php:1354                                                               
  Stack trace:                                                                 
  #0 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Collections/Col  
  lection.php(11): Illuminate\Foundation\Bootstrap\HandleExceptions->handleEr  
  ror()                                                                        
  #1 /var/www/html/pp/vendor/composer/ClassLoader.php(444): include('...')     
  #2 /var/www/html/pp/vendor/composer/ClassLoader.php(322): Composer\Autoload  
  \includeFile()                                                               
  #3 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Collections/hel  
  pers.php(15): Composer\Autoload\ClassLoader->loadClass()                     
  #4 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Pack  
  ageManifest.php(89): collect()                                               
  #5 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Pack  
  ageManifest.php(78): Illuminate\Foundation\PackageManifest->config()         
  #6 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Boot  
  strap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->alias  
  es()                                                                         
  #7 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Appl  
  ication.php(230): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstra  
  p()                                                                          
  #8 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Cons  
  ole/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith()      
  #9 /var/www/html/pp/vendor/laravel/framework/src/Illuminate/Foundation/Cons  
  ole/Kernel.php(127): Illuminate\Foundation\Console\Kernel->bootstrap()       
  #10 /var/www/html/pp/artisan(37): Illuminate\Foundation\Console\Kernel->han  
  dle()                                                                        
  #11 {main}  
  
  
  ------ Edit (later) -----
  have run composer on the folder. Noted issue that I run php8 while composer.json claims I need php7 (will try more)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for providing all the information on the installation process. 

I will take a closer look on them and report back. 

FYI I'm planning to release a single-file installer in order to make things easier to manage moving forward.

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by TheNomad11** [comment]
> Thanks for all your input! This will be fixed for the next version.
> ![](https://camo.githubusercontent.com/61f0c4639d14568d6b538e4dc576a8f652080e5205af19b6a4bb8607ce58d479/68747470733a2f2f63646e2e616c65787473656c6567696469732e636f6d2f706c61696e7061642f6c6f676f732f706c61696e7061642d6f6e6c696e652d7369676e61747572652e706e67) 	Alex Tselegidis, Plainpad Creator
> [Need a customization? Get a free quote!](https://alextselegidis.com)

Has there been a new version? Doesn't seem so? No updates for more than a year. Are you still working on it @alextselegidis ?

**Comment by alextselegidis** [comment]
Hello! 

Yes, the new version will come up shortly. 

I'm currently putting some work together for the next https://github.com/alextselegidis/easyappointments release and then the Plainpad one will follow shortly. 

Stay tuned for more updates. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by gemsling** [comment]
Subscribing to this issue to see any future comments.
Every few months, I have another crack at setting up Plainpad, spending a couple hours reviewing the comments in the various issues here, trying to tweak my config to progress past the login screen.

I love the design of Plainpad, and think it could be exactly what I want, so I'm looking forward to getting it working on my server (Ubuntu + NGINX + MariaDB + PHP 7.4) one day.

For now, though, all I see in my browser console is that HttpClient.js encounters an Internal Server Error when trying to connect to /api.php/v1/, but I get no corresponding entries in my NGINX error_log to give me a clue about why.

**Comment by alextselegidis** [comment]
Quick update on this thread: I'm planning to release an official image for Plainpad so that one can host without much trouble. Will announce this soon 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by raystek** [comment]
I got plainpad set up and the php artesian command ran successfully.

When I log in with admin@example.org and pw 12345, it just goes back to the login screen.

Please advise if anyone.

**Comment by Penworks** [comment]
Following this thread for updates

**Comment by alextselegidis** [comment]
Closing this as the framework was updated to Laravel 12  and thus the setup must be checked again with the new framework version

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
